version: "3.8"

services:
  database:
    container_name: db_rPlace
    image: postgres:16.1
    restart: always
    environment:  
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '5001:5432'
    expose:
      - '5001'
    # networks:
    #   - network_rPlace
    volumes:
      - volume_rPlace:/var/lib/postgresql/data

  back:
    build:
      context: ./back
      dockerfile: ./Dockerfile
    container_name: back_rPlace
    environment:  
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      ROOT_USERNAME: ${ROOT_USERNAME}
      ROOT_PASSWORD: ${ROOT_PASSWORD}
      IP_FRONT: ${IP_FRONT}
      IP_BACK: ${IP_BACK}
      PORT_FRONT: ${PORT_FRONT}
      PORT: ${PORT}
      URL_FRONT: ${URL_FRONT}
      URL_BACK: ${URL_BACK}
    # ports:
    #   - '3000:3000'
    #   - '5555:5555'
    depends_on:
      - database
    # volumes:
    #   - ./back:/app
    # networks:
    #   - network_rPlace

  front:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    container_name: front_rPlace
    environment:
      VITE_IP_BACK: ${VITE_IP_BACK}
      VITE_PORT_BACK: ${VITE_PORT_BACK}
      VITE_URL_BACK: ${VITE_URL_BACK}
    ports:
    #   - '5173:5173'
      - '4001:4001'
    depends_on:
      - back
    # volumes:
    #   - ./front/src:/app/src
    #   - ./front/package.json:/app/package.json
    #   - ./front/package-lock.json:/app/package-lock.json
    # networks:
    #   - network_rPlace

volumes:
  volume_rPlace:
    name: volume_rPlace

# networks:
#   network_rPlace:
#     name: network_rPlace